export const messageRespone = {
  NAME_MUST_BE_STRING: 'Name must be type String',
  NAME_NOT_EMPTY: 'Id must be ObjectID',
  ID_MUST_BE_NOT_EMPTY: 'Id Not Empty',
  ID_MUST_BE_OBJECTID: 'Id must be ObjectID',
  PRICE_MUST_NOT_EMPTY: 'price not empty',
  QUALITY_NOT_EMPTY: 'quality not empty',
  CREATE_SUCCESS: 'create success',
  UPDATE_SUCCESS: 'update success',
  GET_SUCCESS: 'Get success',
  DELETE_SUCCESS: 'Delete success',
  ORDER_NOT_FOUND: 'Order Not Found',
  VERIFY_FAILED: 'Verify Signed Failed',
  ORDER_NOT_COMPLETED: 'Order is not complete',
  PAIED: 'Paied',
  NOT_FOUND_FILE: 'Not found file',
  UPLOAD_IMAGE_SUCCESS: 'Upload image success',
  GET_IMAGE_SUCCESS: 'Get image success',
  GET_LIST_SUCCESS: 'Get List Success',
  Id_not_format: 'Id not format',
  FORBIDENT: 'Forbident',
  NOT_DELETE_THIS_ACCOUNT: 'Not Delete This Account',
  LOGOUT_SUCCESS: 'Logout Success',
  ORDER_WAS_PAIED: 'Order was paied',
  NOT_FOUND_DISCOUNT: 'Not Found Discount',
  DISCOUNT_EXPIRED: 'Discount Expired',
  USER_NOT_SPORT_DISCOUNT: 'User not sport discount',
  USER_NOT_FOUND: 'User not found',
  ACCOUNT_NOT_VERIFY: 'Account not verify',
  TOKEN_NOT_FOUND: 'Token Not Found',
  CODE_NOT_FOUND: 'Code Not Found',
  LOGIN_SUCCESS: 'Login Success',
  YOUR_CODE_NOT_MATCH: 'Your code not match',
  VERIFY_SUCCESS: 'Verify Success',
  PASSWORD_TOO_SHORT: 'Password too short',
  PASSWORD_AND_CONFIRMPASS_NOT_MATCHES: 'Password and Confirm Password not matches',
  PASSWORD_AND_OLDPASSWORD_NOT_MATCHES: 'Password and OldPassword not matches',
  WRONG_PASSWORD: 'Wrong Password',
  CATEGORY_IS_EXITS: 'Category is Exits',
  CATEGORY_NOT_EXITS: 'Category not Exits',
  NAME_IS_EXITS: 'Name is Exits',
  PASSWORD_NOT_FOUND_OR_NOT_EMPTY: 'Password not found or not empty',
  USER_NOT_VERIFY: 'User not verify',
  CART_NOT_FOUND: 'Cart not found',
  COUPON_CODE_HAS_EXPIREDEXPIRED: 'Coupon code has expired',
  ORDER_SUCCESS: 'Order Success',
  EMAIL_EXITS: 'Email Exits ',
  NOT_FOUND_CODE: 'Not Found Code',
  Invalid_PIN: 'Invalid PIN',
  CHANGE_PASSWORD_SUCCESS: 'Change Password Success',
  ADD_TO_CART_SUCCESS: 'Add to cart success'
} as const
